# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-12 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField()),
                ('del_falg', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 12, 14, 37, 58, 12000), null=True)),
            ],
            options={
                'db_table': 'sys_role',
            },
        ),
    ]
